name: CI-CD with Environments

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Complie
        run: echo Hello, lendly!

  Development:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: "http://dev.demoApp.com"
    steps:
      - name: Deploy
        run: echo I am deploying to dev env

  Staging:
    name: Deploy to Staging
    if: github.event.ref== 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: "http://dev.test_demoApp.com"
    steps:
      - name: Deploy
        run: echo I am deploying to staging env

  Production:
    name: Deploy to production
    needs: [Staging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "http://www.demoApp.com"
    steps:
      - name: Deploy
        run: echo I am deploying to prod env
