name: CI-CD with Environments

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Complie
        run: echo Hello, lendly!

  Development:
    name: Deploy to Dev
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: "http://dev.demoApp.com"
    steps:
      - name: Deploy
        run: echo I am deploying to dev env

  Staging:
    name: Deploy to Staging
    if: github.event.ref== 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: "http://dev.test_demoApp.com"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Deploy
        run: echo I am deploying to staging env

  Production:
    name: Deploy to production
    needs: [Staging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "http://www.demoApp.com"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{secrets.WIF_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT}}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          workload_identity_pool: ${{secrets.WORKLOAD_IDENTITY_PROVIDER_ID}}
          workload_identity_principal: ${{secrets.SERVICE_ACCOUNT}}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Send Context to GCS
        run: |
          commit_hash=$(git rev-parse HEAD)     
          echo '${{ toJson(github) }}' > "production-deployment-${commit_hash}.json"     
          gsutil cp "production-deployment-${commit_hash}.json" gs://dora-github-production-deployment/
