name: Production Deployment metadata to GCS

on:
  workflow_run:
    workflows: ["CI-CD with Environments"]
    types:
      - completed

jobs:
  setup-prepare-list:
    name: Environment Checking
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{secrets.WIF_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT}}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          workload_identity_pool: ${{secrets.WORKLOAD_IDENTITY_PROVIDER_ID}}
          workload_identity_principal: ${{secrets.SERVICE_ACCOUNT}}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Debug GitHub Event
        run: echo "${{ toJson(github.event) }}"

      - name: Generate and Upload Production Metadata to GCS
        if: github.event.deployment.environment == 'production'
        run: |
          commit_hash=$(git rev-parse HEAD)
          workflow_run_number=$(echo "${{ github.event.workflow_run.url }}" | awk -F'/' '{print $NF}')
          branch_name=$(echo "${{ github.event.deployment.ref }}" | awk -F'/' '{print $NF}')

          echo '{ "github": '"$(echo "${{ toJson(github) }}" | jq --arg commit_hash "${commit_hash}" --arg workflow_run_number "${workflow_run_number}" --arg branch_name "${branch_name}" '. + { "commit_hash": $commit_hash, "workflow_run_number": $workflow_run_number, "branch_name": $branch_name }')" }' > "production-deployment-${commit_hash}.json"

          gsutil cp "production-deployment-${commit_hash}.json" gs://dora-github-production-deployment/
