# name: Push Metadata to GCS

# on:
#   push:
#     branches: ["main"]

# jobs:
#   setup-prepare-list:
#     name: DORA-PUSH-EVENT-POC
#     runs-on: ubuntu-latest

#     permissions:
#       contents: "read"
#       id-token: "write"

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       # Configure Workload Identity Federation and generate an access token.
#       - id: "auth"
#         name: "Authenticate to Google Cloud"
#         uses: "google-github-actions/auth@v1"
#         with:
#           create_credentials_file: true
#           workload_identity_provider: ${{secrets.WIF_PROVIDER}}
#           service_account: ${{secrets.SERVICE_ACCOUNT}}

#       - name: Set up Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v0.3.0
#         with:
#           workload_identity_pool: ${{secrets.WORKLOAD_IDENTITY_PROVIDER_ID}}
#           workload_identity_principal: ${{secrets.SERVICE_ACCOUNT}}
#           project_id: ${{secrets.GCP_PROJECT_ID}}

#       - name: Generate and Upload GitHub Context to GCS
#         run: |
#           commit_hash=$(git rev-parse HEAD)
#           echo '${{ toJson(github) }}' > "github-context-${commit_hash}.json"
#           gsutil cp "github-context-${commit_hash}.json" gs://dora-github-push-event/
