name: Metadata to GCS

on:
  push:
    branches: ["main"]

jobs:
  setup-prepare-list:
    name: WIF Test
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/541105984323/locations/global/workloadIdentityPools/lc-wif-pool/providers/lc-wif-provider"
          service_account: "lendly-wif@off-net-dev.iam.gserviceaccount.com"

      # List the instances in the project
      - name: List Instances
        run: |-
          gsutil ls -p off-net-dev
